<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:wcpts itemname="完成品图示" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:wcpts>

<field:tsqk itemname="特殊情况" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:tsqk>
