<?php
$z[0]=Array("global","",347,370);
$z[0][4]['name']="cfg_skin";
$z[1]=Array("global","",552,575);
$z[1][4]['name']="cfg_skin";
$z[2]=Array("channelartlist","\r\n            <li class=\"gnb-01 {dede:field.currentstyle/}\"><a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n              <ul class=\"clearfix gnb-ul-depth02 activeDepth02\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li><a href='[field:typelink/]' class='has-list'>[field:typename/]</a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",747,1253);
$z[2][4]['typeid']="top";
$z[2][4]['row']="8";
$z[2][4]['currentstyle']="active";
$z[3]=Array("global","",1342,1365);
$z[3][4]['name']="cfg_skin";
$z[4]=Array("global","",1474,1499);
$z[4][4]['name']="cfg_phpurl";

?>