<?php
$z[0]=Array("field","",523,545);
$z[0][4]['name']="typename";
$z[1]=Array("global","",546,572);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",614,639);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",669,692);
$z[3][4]['name']="cfg_skin";
$z[4]=Array("include","",936,971);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1273,1296);
$z[5][4]['name']="cfg_skin";
$z[6]=Array("field","",1427,1456);
$z[6][4]['name']="position";
$z[7]=Array("field","",1506,1528);
$z[7][4]['name']="typename";
$z[8]=Array("channel","\r\n                <li>\r\n                  <button type=\"button\" class=\"setting\">\r\n                  <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                  </button>\r\n                </li>\r\n                ",2014,2521);
$z[8][4]['type']="son";
$z[8][4]['noself']="yes";
$z[8][4]['currentstyle']="<li> <button type='button' class='setting selected'> <a href='~typelink~' ~rel~>~typename~</a> </button> </li>";
$z[9]=Array("arclist","\r\n              <dl class=\"type-03\">\r\n                <dt>\r\n                  <h4>[field:shorttitle/]</h4>\r\n                </dt>\r\n                <dd class=\"first\"><strong>[field:description/]</strong><span class=\"detail\">[field:title /]</span></dd>\r\n              </dl>\r\n              <hr class=\"type-01 clear\">\r\n              ",2603,3013);
$z[9][4]['titlelen']="60";
$z[9][4]['row']="8";
$z[9][4]['orderby']="aid";
$z[9][4]['orderway']="desc";
$z[10]=Array("include","",3101,3142);
$z[10][4]['filename']="index_left.htm";
$z[11]=Array("include","",3187,3224);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("global","",3268,3291);
$z[12][4]['name']="cfg_skin";
$z[13]=Array("global","",3342,3365);
$z[13][4]['name']="cfg_skin";

?>