<?php
$z[0]=Array("channelartlist","\r\n      <li class=\"lnb-01\"><a href=\"javascript:;\" class=\"{dede:field.currentstyle/}\">{dede:field.typename/}</a>\r\n        <ul>\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",137,532);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";
$z[0][4]['currentstyle']="on open";
$z[1]=Array("type","[field:typeurl/]",635,685);
$z[1][4]['typeid']="6";
$z[2]=Array("global","",697,720);
$z[2][4]['name']="cfg_skin";
$z[3]=Array("global","",777,800);
$z[3][4]['name']="cfg_skin";
$z[4]=Array("global","",857,880);
$z[4][4]['name']="cfg_skin";
$z[5]=Array("type","[field:typeurl/]",940,990);
$z[5][4]['typeid']="4";
$z[6]=Array("global","",1021,1044);
$z[6][4]['name']="cfg_skin";

?>